name: CI

on:
  push:
    branches:
      - main
<<<<<<< HEAD
  pull_request:

env:
  NODE_VERSION: 14
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_number }}
  PERCY_PARALLEL_TOTAL: 1

jobs:
  lint:
    name: Lint files and dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint


  test-app:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npx percy exec -- npm run test
        env:
          PERCY_PARALLEL_NONCE: ${{ env.PERCY_PARALLEL_NONCE }}
          PERCY_PARALLEL_TOTAL: ${{ env.PERCY_PARALLEL_TOTAL }}
          PERCY_TOKEN: 8e2dcd58fd11befd29a6d3d3db63b7fcb833986866960d5b9d0d9c4393ba6ff2
=======
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
>>>>>>> b7a0a3d (v3.26.0...v4.0.1)
